name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          # Username used to log against the Docker registry
          username: jaychangani13
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Specifies whether the given registry is ECR (auto, true or false)
          ecr: auto
          # Log out from the Docker registry at the end of a job
          logout: true

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag jaychangani13/TweetsClassification:1.0
      - name: Push the docker image
        run: docker push jaychangani13/TweetsClassification:1.0
